/* eslint-disable max-len */
// TODO: refactor
enum Errors {
  TrezorSignTxError = 'Error occured while signing the transaction with Trezor',
  HwTransportNotFoundError = 'Error occured while trying to find hw transport, make sure Ledger or Trezor is connected to you computer',
  InvalidPathError = 'Can not parse path',
  InvalidFileTypeError = 'Invalid file type of hw-signing-file',
  InvalidHwSigningFileError = 'Invalid file contents of hw-signing-file',
  InvalidTxBodyFileError = 'Invalid file contents of tx-body-file',
  TxSerializationMismatchError = 'Tx serialization mismatch',
  MissingHwSigningDataAtPathError = 'Can not find hw signing data',
  MultipleWitnessesError = 'Multiple witnesses found',
  UndefinedCommandError = 'command undefined',
  MissingSigningFileError = 'missing signing file',
  UnknownCertificateTypeError = 'unknown certificate type',
  MultipleCertificatesWithPoolRegError = 'Multiple pool registration certificates found, expected one',
  WithdrawalIncludedWithPoolRegError = 'Withdrawal certificate and pool registration certificate found, expected one',
  PaymentFileInlucedWithPoolRegError = 'Unexpected payment hardware signing file with pool registration certificate found',
  MultipleStakingSigningFilesWithPoolRegError = 'Multiple staking signing files with pool registration certificate found, expected only one staking signing file',
  MissingPaymentSigningFileError = 'Missing payment hardware signing file',
  TooManySigningFilesError = 'Too many signing files',
  MissingStakingSigningFileError = 'Missing staking signing file',
  MissingInputError = 'Missing input',
  MissingOutputError = 'Missing output',
  TrezorError = 'Trezor operation failed, please make sure you are using the latest version of Trezor firmware',
  TxInputParseError = 'Failed to parse input',
  TxOutputParseError = 'Failed to parse output',
  WithrawalsParseError = 'Failed to parse withdrawals',
  TxStakingKeyRegistrationCertParseError = 'Failed to parse staking key registration certificate',
  TxStakingKeyDeregistrationCertParseError = 'Failed to parse staking key deregistration certificate',
  TxDelegationCertParseError = 'Failed to parse delegation certificate',
  TxStakepoolRegistrationCertParseError = 'Failed to parse stakepool registration certificate',
  TxSingleHostIPRelayParseError = 'Failed to parse single host IP relay',
  TxSingleHostNameRelayParseError = 'Failed to parse single host name relay',
  TxMultiHostNameRelayParseError = 'Failed to parse multi host name relay',
  MissingSigningFileForCertificateError = 'Missing signing file for certificate',
  OwnerMultipleTimesInTxError = 'Owner multiple times in tx',
  UnsupportedRelayTypeError = 'Unsupported relay type',
  UnknownCertificateError = 'Unknown certificate',
  UnsupportedCertificateTypeError = 'Unsupported certificate type',
  MissingSigningFileForWithdrawalError = 'Missing signing file for withdrawal',
  CantSignTxWithPoolRegError = 'Can not sign trasaction with pool registration',
  InvalidAddressError = 'Invalid address',
  LedgerOperationError = 'Ledger operation error',
}

export {Errors}
