// config intended to be passed on to frontend
module.exports = {
  CARDANOLITE_BLOCKCHAIN_EXPLORER_URL:
    process.env.CARDANOLITE_BLOCKCHAIN_EXPLORER_URL,
  CARDANOLITE_TRANSACTION_SUBMITTER_URL:
    process.env.CARDANOLITE_TRANSACTION_SUBMITTER_URL,
  CARDANOLITE_ADDRESS_RECOVERY_GAP_LENGTH:
    process.env.CARDANOLITE_ADDRESS_RECOVERY_GAP_LENGTH,
  CARDANOLITE_FORCE_HTTPS: process.env.CARDANOLITE_FORCE_HTTPS,
}
